name: Slack Cleaner

on:
  schedule:
    - cron:  '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/calculate-dates-and-times@v1.0.2
        id: before
        with:
          subtract: 7 days
          format: YYYYMMDD
      - uses: docker://sgratzl/slack-cleaner@sha256:6aa23eb817c5fde2dd6157e2454b401318f11f6433c673aa48783d96d4dc95d5
        name: 'Clear #notifications channel'
        with:
          args: |
            --token ${{ secrets.SLACK_TOKEN }}
            --quiet
            --message
            --bot
            --after ${{ steps.before.outputs.date }}
            --channel notifications
